Pull request Develop to Main
tms-dos21-onl/igor-vanin pull request #14
Opened 2024-03-11 22:00 UTC by Rvlt135

Pull Request с выполнением задания 8 для ветки develop

2024-03-29 14:41 UTC, AlexPykavy commented on LICENSE.md
Какая-то здесь лицензия некрасивая :)

Мне кажется, что ты не совсем правильно скачал MIT лицензию с GitHub: тебе нужно было использовать т.н. raw ссылку - https://raw.githubusercontent.com/git/git-scm.com/main/MIT-LICENSE.txt.

А потом при мерже, ты решил оставить обе лицензии, хотя надо было одну.

Сделай, пожалуйста, один коммит поверх всех существующих, где ты поменяешь содержимое этого файла на правильную MIT лицензию.

2024-03-29 14:48 UTC, AlexPykavy commented on homework-8/.github/workflow/validate-shell.yaml
Походу ты попытался этот файлик скачать через `curl`/`wget`, а они его не смоги найти, т.к. были выполнены без авторизации в GitHub, и вернули `404`. Можешь, пожалуйста, вручную скачать через web-браузер и подложить его сюда?

2024-03-29 14:48 UTC, AlexPykavy requested changes
Поправь, пожалуйста, эти 2 момента

2024-04-01 20:17 UTC, Rvlt135 commented
LICENSE поправил, но почему то здесь в change он отображается с большим отступом, а на сервере у меня все нормально.

2024-04-08 13:01 UTC, AlexPykavy approved these changes
Сейчас всё чётко! Апруфф

2024-04-08 13:01 UTC, merged